# ????????? ???? ??????
app.db.url=jdbc:postgresql://localhost:5432/supply_db
app.db.user=postgres
app.db.password=1111

# ????????? ???????
app.port=9090
app.threads=16

# ????????????? ?? ?????????
app.admin.user=admin
app.admin.password=admin123

# ?????????????? ????? ???? ?????? ??? ??????? (?????? ??? ??????????)
# app.users.reset=false